DROP SCHEMA PUBLIC CASCADE;
CREATE SCHEMA PUBLIC;

CREATE TABLE property (
  id BIGSERIAL PRIMARY KEY,
  license CHAR(36) UNIQUE NOT NULL,
  pin CHAR(7) UNIQUE NOT NULL,
  owner VARCHAR NOT NULL,
  email VARCHAR NOT NULL,
  location VARCHAR NOT NULL,
  joined VARCHAR NOT NULL
);

CREATE TABLE session (
  id BIGSERIAL PRIMARY KEY,
  property_id BIGINT REFERENCES property(id),
  mowed BOOLEAN NOT NULL,
  edged BOOLEAN NOT NULL,
  cleaned BOOLEAN NOT NULL,
  trimmed BOOLEAN NOT NULL,
  fertilized BOOLEAN NOT NULL,
  pesticided BOOLEAN NOT NULL,
  weeded BOOLEAN NOT NULL,
  watered BOOLEAN NOT NULL,
  repaired BOOLEAN NOT NULL,
  note VARCHAR,
  occured VARCHAR NOT NULL
);